classdef HJBSolver
	% A solver for the Hamilton-Jacobi-Bellman equation.
	% Implicit and implicit-explicit solution methods are
	% provided.
	%
	% The recommended use of this class is to first create
	% a Params object and an Income object, and pass these
	% to the HJBSolver constructor. Alternatively, one can
	% use other objects that satisfy the requirements laid
	% out in the properties block.

	properties (Constant)
		% Update this array when the required parameters
		% change.
		required_parameters = {'nb', 'na', 'nz',...
			'rho', 'rhos', 'deathrate'};

		% Update this array when the required income
		% variables change.
		required_income_vars = {'ny', 'ytrans'};
	end

	properties (SetAccess=protected)
		%	An object with the following required attributes:
		%
		%		nb, na, nz
		%
		%		rho > 0
		%		- The time discount factor.
		%
		%		rhos
		%		- A vector indicating all possible values for rho.
		%		  If there is no rho heterogeneity, set rhos = [].
		%
		%		deathrate > 0
		%
		%		SDU
		%		- A boolean indicator, true if using stochastic
		%		  differential utility and false otherwise.
		p;

		%	An object with the following required attributes:
		%
		%		ny
		%	
		%		ytrans
		%		- The income transition matrix, should have row sums
		%		  of zero and shape (ny, ny).
		%
		%	and if using stochastic differential utility, the following
		%	is a required method:
		%
		%		income_transitions_SDU(p, V)
		%		- Must accept two arguments, p and V, and must return
		%		  an array of shape (nb*na*nz, ny, ny) to be used as
		%		  the adjusted income transition rates.
		%
		%	and--again for stochastic differential utility, the following
		%	method is required, or 'sparse_income_transitions' can be
		%	an attribute of the 'income' variable, in which case it must
		%	be a sparse array of size (nb*na*nz*ny, nb*na*nz*ny) indicating
		%	the adjusted income transition rates:
		%
		%		income_transition_matrix_SDU(p, ez_adj, 'HJB')
		%		- Must accept the three arguments above. The variable
		%		  'ez_adj' is the array generated by the
		%		  income_transitions_SDU() method.
		income;

		% Total number of states.
		n_states;

		% Number of states per income level.
		states_per_income;

		% Number of states along each dim, a vector.
		shape;

		% Sparse matrix of discount factors.
		rho_mat;
        
        % An HJBOptions object.
        options;

        % Current iteration, needed for the HIS.
        current_iteration = 0;
	end

	methods
		function obj = HJBSolver(p, income, options)
			% See the properties block above or view this class'
			% documentation to see the requirements of the
			% input parameters.

			import HACT_Tools.options.HJBOptions

			% ---------------------------------------------------------
			% Validate Input Arguments and Set Options
			% ---------------------------------------------------------
			obj.check_parameters(p);
			obj.p = p;

			obj.check_income(income);
			obj.income = income;

			if exist('options', 'var')
				assert(isa(options, 'HJBOptions'),...
					"options argument must be a HJBOptions object");
				obj.options = options;
			else
				obj.options = HJBOptions();
			end

			obj.n_states = p.nb * p.na * p.nz * income.ny;
			obj.states_per_income = p.nb * p.na * p.nz;
			obj.shape = [p.nb p.na p.nz income.ny];

			assert(~p.SDU,...
					[	"Model uses stochastic differential utility, ",...
						"the SDU subclass must be used instead"])

			% ---------------------------------------------------------
			% Discount Factor Matrix
			% ---------------------------------------------------------
			obj.create_rho_matrix();
		end

		function V_update = solve(obj, A, u, V, varargin)
			% Updates the value function.

			obj.check_inputs(A, u, V);

			if obj.options.implicit
				V_update = obj.solve_implicit(A, u, V, varargin{:});
			else
				V_update = obj.solve_implicit_explicit(A, u, V, varargin{:});
			end
		end
	end

	methods (Access=protected)
		function create_rho_matrix(obj)
			if obj.options.implicit
				% discount factor values
		        if numel(obj.p.rhos) > 1
		            rhocol = repmat(kron(obj.p.rhos(:), ones(obj.p.nb*obj.p.na, 1)), obj.income.ny, 1);
		            obj.rho_mat = spdiags(rhocol, 0, obj.n_states, obj.n_states);
		        else
		            obj.rho_mat = obj.p.rho * speye(obj.n_states);
		        end
		    else
		    	if numel(obj.p.rhos) > 1
			        rhocol = kron(obj.p.rhos(:), ones(p.nb*p.na,1));
			        obj.rho_mat = spdiags(rhocol, obj.states_per_income, obj.states_per_income);
			    else
			        obj.rho_mat = obj.p.rho * speye(obj.states_per_income);
			    end
	    	end
		end

		function check_inputs(obj, A, u, V)
			import HACT_Tools.Checks;

			Checks.is_square_sparse_matrix(A, obj.n_states);
			Checks.has_shape(u, obj.shape);
			Checks.has_shape(V, obj.shape);
		end

		function check_if_SDU(obj)
			assert(~obj.p.SDU,...
				[	"Model uses stochastic differential utility, "...
					"the appropriate subclass should be used"])
		end

		%%--------------------------------------------------------------
	    % Implicit Updating
	    % --------------------------------------------------------------
		function Vn1 = solve_implicit(obj, A, u, V, varargin)
			assert(obj.p.deathrate == 0, "Fully implicit assumes no death.")

	        % add income transitions
	        if obj.p.SDU
	        	B = A + obj.income.income_transition_matrix_SDU(obj.p, V);
	        else
	        	B = A + kron(obj.income.ytrans, speye(obj.states_per_income));
	        end

	        % The user may want to overload the method called here.
	        obj.get_RHS_implicit(u, V, varargin{:});
	        
	        B = (rho_mat - B) * obj.options.delta + speye(obj.n_states);
	        Vn1 = B \ RHS;
	        Vn1 = reshape(Vn1, obj.p.nb, obj.p.na, obj.p.nz, obj.income.ny);
		end

		function RHS = get_RHS_implicit(obj, u, V, varargin)
			% Computes the right-hand-side of the implicit updating
			% equation. If using stochastic differential utility,
			% HJBSolverSDU should be used, which overloads this method.

			RHS = obj.options.delta * u(:) + Vn(:);
		end

		%%--------------------------------------------------------------
	    % Implicit-Explicit Updating
	    % --------------------------------------------------------------
		function Vn1 = solve_implicit_explicit(obj, A, u, V, varargin)
			obj.current_iteration = obj.current_iteration + 1;

			u_k = reshape(u, [], obj.income.ny);

	        Vn_k = reshape(V, [], obj.income.ny);
	        [Vn1_k, Bk_inv] = obj.loop_over_income_implicit_explicit(Vn_k, A, u, varargin{:});

	        % Howard improvement step
	        if (obj.current_iteration >= obj.options.HIS_start) && (~obj.p.SDU)
	            Vn1_k = obj.howard_improvement_step(Vn1_k, u_k, Bk_inv);
	        end
	        Vn1 = reshape(Vn1_k, obj.p.nb, obj.p.na, obj.p.nz, obj.income.ny);
		end

		function [Vn1_k, Bk_inv] = loop_over_income_implicit_explicit(obj, Vn_k, A, u, varargin)
        	u_k = reshape(u, [], obj.income.ny);

        	Vn1_k = zeros(obj.states_per_income, obj.income.ny);
        	Bk_inv = cell(1, obj.income.ny);
        	for k = 1:obj.income.ny
        		Bk = obj.construct_Bk(k, A);
            	Bk_inv{k} = inverse(Bk);

            	indx_k = ~ismember(1:obj.income.ny, k);

	            offdiag_inc_term = sum(...
	            	repmat(obj.income.ytrans(k,indx_k), obj.states_per_income,1)...
	                .* Vn_k(:,indx_k), 2);

	            RHSk = obj.options.delta * u_k(:,k)...
	            	+ Vn_k(:,k) + obj.options.delta * offdiag_inc_term;
	            
	            Vn1_k(:,k) = Bk_inv{k} * RHSk;
        	end
	    end

		function Bk = construct_Bk(obj, k, A, varargin)
		    % For the k-th income state, constructs the matrix
		    % Bk = (rho + deathrate - A)*delta + I, which serves
		    % as the divisor in the implicit-explicit update scheme.

		    if numel(obj.p.rhos) > 1
		        rhocol = kron(obj.p.rhos(:), ones(obj.p.nb*obj.p.na, 1));
		        rho_mat = spdiags(rhocol, obj.states_per_income, obj.states_per_income);
		    else
		        rho_mat = obj.p.rho * speye(obj.states_per_income);
		    end

		    indx_k = ~ismember(1:obj.income.ny,k);
		    i1 = 1+(k-1)*(obj.states_per_income);
		    i2 = k*(obj.states_per_income);

		    Ak = A(i1:i2, i1:i2);
		    Bk = obj.options.delta * rho_mat...
		    	+ (1 + obj.options.delta * obj.p.deathrate) * speye(obj.states_per_income)...
		        - obj.options.delta * Ak;

		    Bk = Bk - obj.options.delta * get_Bk_income_term(obj, k, varargin{:});
		end

		function inc_term = get_Bk_income_term(obj, k, varargin)
			% Add income transitions to the left-hand-side of
			% the HJB. This method is overloaded for stochastic
			% differential utility.

			inc_term = obj.income.ytrans(k, k) * speye(obj.states_per_income);
		end

		function Vn2_k = howard_improvement_step(obj, Vn1_k, u_k, Bik_all)
		    % Technique to speed up convergence.

		    for jj = 1:obj.options.HIS_maxiters
		        Vn2_k = NaN(obj.states_per_income, obj.income.ny);
		        for kk = 1:obj.income.ny
		            indx_k = ~ismember(1:obj.income.ny, kk);
		            
		            Vkp_stacked = sum(...
		                	repmat(obj.income.ytrans(kk,indx_k),obj.states_per_income,1)...
		                	.* Vn1_k(:,indx_k), 2);
		            qk = obj.options.delta * (u_k(:,kk) + Vkp_stacked) + Vn1_k(:,kk);
		            Vn2_k(:,kk) = Bik_all{kk} * qk;
		        end

		        dst = max(abs(Vn2_k(:) - Vn1_k(:)));
		        Vn1_k = Vn2_k;
		        if dst < obj.options.HIS_tol
		            break
		        end
    		end
		end

		function check_parameters(obj, p)
			HACT_Tools.Checks.has_attributes(....
				p, obj.required_parameters);
		end

		function check_income(obj, income)
			HACT_Tools.Checks.has_attributes(...
				income, obj.required_income_vars);
			HACT_Tools.Checks.is_square_matrix(income.ytrans);
		end
	end
end