function assert_square_sparse(object, required_size)
	% Performs assertions that an input is a square,
	% sparse, nonempty matrix.

	assert(required_size > 0,...
		"Declared size of input must be non-negative")

	assert(ismatrix(object) && (size(object, 1) == size(object, 2)),...
		"Input must be a square matrix")

	assert(issparse(object),...
		"Input must be sparse")

	assert(size(object, 1) == required_size,...
		[	"Input shape does not match the declared dimensions.",...
			"Expected a square matrix of shape (%u, %u), ",...
			"got an array of shape (%u, %u)"
			],...
		required_size, required_size,...
		size(object, 1), size(object, 2));
end